///@package io.alkapivo.visu.ui


///@static
///@type {Struct}
global.__VisuTheme = {
  color: {
    accentLight: "#7742b8",
    accent: "#5f398e",
    accentShadow: "#462f63",
    accentDark: "#231832",
    primaryLight: "#455f82",
    primary: "#3B3B53",
    primaryShadow: "#2B2B35",
    primaryDark: "#222227",
    sideLight: "#212129",
    side: "#1B1B20",
    sideShadow: "#141418",
    sideDark: "#0D0D0F",
    button: "#3B3B53",
    buttonHover: "#3c4e66",
    text: "#D9D9D9",
    textShadow: "#878787",
    textFocus: "#ededed",
    textSelected: "#7742b8",
    accept: "#3d9e87",
    acceptShadow: "#368b77",
    deny: "#9e3d54",
    denyShadow: "#6d3c54",
    ruler: "#E64B3D",
    header: "#963271",
    stick: "#5f398e",
    stickHover: "#7742b8",
    stickBackground: "#0D0D0F",
  },
}
#macro VisuTheme global.__VisuTheme


///@type {Map<String, Callable>}
global.__VisuStyles = new Map(String, Callable, {
  "menu-title": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_28_bold",
      color: VisuTheme.color.text,
      enableColorWrite: false,
    },
  },
  "menu-button-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      //offset: { x: 24 },
      enableColorWrite: false,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
      backgroundAlpha: 0.75,
    },
  },
  "menu-label-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      offset: { x: 24 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      //backgroundColor: VisuTheme.color.side,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.accentShadow,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
      backgroundAlpha: 0.05,
    },
  },
  "menu-button-input-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      outline: true,
      outlineColor: VisuTheme.color.side,
      offset: { x: 24 },
      enableColorWrite: false,
      //colorHoverOver: VisuTheme.color.accentLight,
      //colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
    input: {
      label: {
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
        font: "font_kodeo_mono_18_bold",
        color: VisuTheme.color.textFocus,
        enableColorWrite: false,
        colorHoverOver: VisuTheme.color.accentLight,
        colorHoverOut: VisuTheme.color.sideDark,
        //backgroundColor: VisuTheme.color.side,
        backgroundAlpha: 0.75,
        backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
  },
  "menu-spin-select-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      outline: true,
      outlineColor: VisuTheme.color.side,
      offset: { x: 24 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      //colorHoverOver: VisuTheme.color.accentLight,
      //colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
    previous: {
      sprite: {
        name: "texture_menu_button_previous",
        blend: VisuTheme.color.textFocus,
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 3 },
    },
    preview: {
      label: {
        align: { v: VAlign.CENTER, h: HAlign.CENTER },
        font: "font_kodeo_mono_18_bold",
        color: VisuTheme.color.textFocus,
        enableColorWrite: false,
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      backgroundMargin: { top: 6, left: 3, bottom: 6, right: 3 },
      backgroundAlpha: 0.75,
    },
    next: {
      sprite: {
        name: "texture_menu_button_next",
        blend: VisuTheme.color.textFocus,
      },
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      backgroundMargin: { top: 6, left: 3, bottom: 6, right: 6 },
      backgroundAlpha: 0.75,
    },
  },
  "menu-keyboard-key-entry": {
    label: {
      align: { v: VAlign.CENTER, h: HAlign.LEFT },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.text,
      offset: { x: 24 },
      useScaleWithOffset: true,
      enableColorWrite: false,
      outline: true,
      outlineColor: VisuTheme.color.side,
      //colorHoverOver: VisuTheme.color.accentLight,
      //colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    },
    preview: {
      align: { v: VAlign.CENTER, h: HAlign.CENTER },
      font: "font_kodeo_mono_18_bold",
      color: VisuTheme.color.textFocus,
      enableColorWrite: false,
      colorHoverOver: VisuTheme.color.accentLight,
      colorHoverOut: VisuTheme.color.sideDark,
      //backgroundColor: VisuTheme.color.side,
      backgroundAlpha: 0.75,
      backgroundMargin: { top: 6, left: 6, bottom: 6, right: 6 },
    }
  },
})
#macro VisuStyles global.__VisuStyles